name: Publish package to GitHub Packages
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - run: echo LIB_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'v' -f 1 | rev ) >> ${GITHUB_ENV}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@millionscard'
      - run: npm version ${{ env.LIB_VERSION }} --no-git-tag-version
      # Ideally we would want the action to compile the library, but we will need a special git token for that
      # - run: npm install
      # - run: npx tsc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
